name: HRM Image build pipeline

on:
  push:
    branches:
    - release-mvp-0.6 # Trigger only on the release branch
  workflow_dispatch:
    # Enable manual triggering

jobs:
  code-scan-and-build:
    runs-on: blacksmith-2vcpu-ubuntu-2204-arm
    environment: dev
    strategy:
      matrix:
        service:
        - front-end # Add all microservice folder

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 3: Build Docker Image for ${{ matrix.service }}
    - name: Build Docker Image for ${{ matrix.service }}
      run: |
        cd ${{ matrix.service }}
        docker build -t tracktwok/smart_hr_system:${{ matrix.service }} .

    # Step 4: Push Docker Image to Registry (Optional)
    - name: Push Docker Image to Registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push tracktwok/smart_hr_system:${{ matrix.service }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
