name: HRM Image build pipeline

on:
  push:
    branches:
    - release-mvp-0.6 # Trigger only on the release branch
  workflow_dispatch:
    # Enable manual triggering

jobs:
  code-scan-and-build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        service:
        - client-master # Add all microservice folder

    steps:
    # # Step 1: Set up QEMU to enable cross-platform builds
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    #   # Step 2: Set up Docker Buildx (for multi-architecture builds)
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    # # Step 3: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 4: Build Docker Image for ${{ matrix.service }}
    - name: Build Docker Image for ${{ matrix.service }}
      run: |
        cd ${{ matrix.service }}
        docker build -t tracktwok/smart_hr_system:${{ matrix.service }} .

    # Step 5: Push Docker Image to Registry
    - name: Push Docker Image to Registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push tracktwok/smart_hr_system:${{ matrix.service }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: code-scan-and-build
    runs-on: ubuntu-latest
    environment: dev

    steps:
    # Step 1: Set up SSH to connect to the EC2 instance
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Step 2: Deploy to EC2
    - name: Deploy Docker Containers on EC2
      run: |
        # Define service variable on the remote server
        SERVICE=${{ matrix.service }}

        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'



        echo "Deploying service: $SERVICE"
        # Pull the latest Docker image

        docker pull tracktwok/smart_hr_system:$SERVICE
        # Stop any running container of this service

        docker rm -f $SERVICE || true
        # Run the container

        docker run -d --name $SERVICE -p 8009:8009 tracktwok/smart_hr_system:$SERVICE
        EOF
