name: Code Scan and Build Docker Images

on:
  push:
    branches:
      - release-mvp-0.6  # Trigger only on the release branch
  workflow_dispatch:  # Enable manual triggering

jobs:
  code-scan-and-build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        service:
          - dashboard-api  # Add all microservice folders here

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run Code Scan
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: 'python'  # Adjust based on the language(s) in your services
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Step 3: Build Docker Image
      - name: Build Docker Image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest .

      # Step 4: Push Docker Image to Registry (Optional)
      - name: Push Docker Image to Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
